@baseUrl = http://localhost:3000/api
#categories
# @name getAllCategories
GET {{baseUrl}}/products?id=6
###


# @name addNewCategories
POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "Laptop"
}
###
# @name pagination
GET {{baseUrl}}/products?_page=1&_limit=2
###

# @name updateCategories
PATCH {{baseUrl}}/products/3
Content-Type: application/json

{
    "name": "Laptop Dell 2021"
}

###
# @name delateCategories
DELETE  {{baseUrl}}/products/2
Content-Type: application/json
